### ISSUE TITLE
[FE] Описание стека проекта

### ISSUE THREAD

**Issue by l3r8yJ** [Handmade-Portal/docs#10]
Добавить описание стека проекта в [вики](https://github.com/Handmade-Portal/docs/wiki/Tech-stack) – [пример](https://github.com/Blamer-io/docs/wiki/Technical-Stack)

**Comment by trapvpack** [comment]
Сделал описания стека по фронтенду - https://github.com/Handmade-Portal/docs/wiki/Tech-stack @SergeyShapovaIov
