### ISSUE TITLE
[DI] Создать страницу в вики

### ISSUE THREAD

**Issue by l3r8yJ** [Handmade-Portal/docs#11]
Добавить страницу в вики, по примеру существующих и заполнить ее:

- [x] ссылки на макеты
- [x] цветовую схему
- [x] иконку в `png` и `svg`

**Comment by thelisass** [comment]
https://github.com/Handmade-Portal/docs/wiki/UI-UX-design

**Comment by ssh4rd** [comment]
@thelisass Картинки как будто нарушают читаемость. Попробуй изменить размер картинок (сделай их чуть поменьше).
Вот статейка на эту тему - https://shorturl.at/dvyU9
