### ISSUE TITLE
[BE] SPIKE linter for projcets

### ISSUE THREAD

**Issue by l3r8yJ** [Handmade-Portal/docs#19]

**Comment by Japsty** [comment]
Вот эта статья помогала с выбором линтеров, но ей 4 года: https://habr.com/ru/articles/457970/
Для go есть либа, в которой собрано множество разных линтеров: https://github.com/golangci/awesome-go-linters

В этой либе собрано около 50 линтеров, но по дефолту подключены только 6. Вот тут список всех доступных литеров в либе: https://golangci-lint.run/usage/linters/

Этот агрегатор линтеров имеет гибкую настройку через yaml/json, вывод тоже настраиваемый, также можно настроить на скольких ядрах будут запускаться линтеры, т.е. он еще поддерживает конкурентность.

Судя по их документации его можно прикрутить к GitHub Actions: https://golangci-lint.run/usage/install/

Поставил себе его на IDE, вот настройка и результат прогона: 

![Image](https://github.com/Handmade-Portal/docs/assets/106777685/8fd6bd6a-82c1-4207-a054-fdb22d804fad)

Документация Editorconfig для Goland: https://www.jetbrains.com.cn/en-us/help/go/editorconfig.html

Ниже пример создания и содержание файла EditorConfig


![Image](https://github.com/Handmade-Portal/docs/assets/106777685/c178ac60-57cc-452f-b702-cc0199e13f6b)



![Image](https://github.com/Handmade-Portal/docs/assets/106777685/02a1bfbf-8c07-469a-acca-150dc50ef356)
