### ISSUE TITLE
Colors scheme

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#2]

**Comment by thelisass** [comment]
![Палитра](https://github.com/Handmade-Portal/docs/assets/154837153/8c0c9d15-e72e-4923-ab5f-8315eef49c4f)


Цвета основного спектра (используются в основных элементах, изображениях):
1. [#e7a7bb](https://vk.com/im?sel=248278105&st=%23e7a7bb) (RGB = 231; 167; 187)
2. [#d1b4e7](https://vk.com/im?sel=248278105&st=%23d1b4e7) (RGB = 209; 180; 231)
3. [#ccdec6](https://vk.com/im?sel=248278105&st=%23ccdec6) (RGB = 204; 222; 198)
4. [#ffe2a6](https://vk.com/im?sel=248278105&st=%23ffe2a6) (RGB = 255; 226; 166)

Дополнительные цвета (используются редко):
1. [#f8bb9c](https://vk.com/im?sel=248278105&st=%23f8bb9c) (RGB = 248; 187; 156)
2. [#cee8ff](https://vk.com/im?sel=248278105&st=%23cee8ff) (RGB = 206; 232; 255)

Оттенки основных и дополнительных цветов (используются для мелких элементов при необходимости):
1. #624478 (RGB = 98; 68; 120)
1. [#6a8473](https://vk.com/im?sel=248278105&st=%236a8473) (RGB = 106; 132; 115)
1. [#29669c](https://vk.com/im?sel=248278105&st=%2329669c) (RGB = 41; 102; 156)
