### ISSUE TITLE
[FE] SPIKE linter

### ISSUE THREAD

**Issue by l3r8yJ** [Handmade-Portal/docs#20]

**Comment by trapvpack** [comment]
1.	**Линтер для Vue3** - https://github.com/vuejs/eslint-plugin-vue 
Документация - https://eslint.vuejs.org/user-guide/
Популярный на github линтер для Vue3 с поддержкой TS 

> Возможно пригодится конфиг Eslint для TS - https://github.com/vuejs/eslint-config-typescript

2.	**Линтер для БЭМ** – bemhint предоставляет возможность работать с JS файлами с помощью плагинов, но эту возможность покрывает Eslint. Из bemhint можно воспользоваться плагином для валидации в css-файлах для чистоты кода и правильного написания, но непонятно может ли он валидировать SCSS файлы, что является необходимостью - https://github.com/bemhint/bemhint-css-naming.
3.	**Для html файлов** можно воспользоваться html-validate, легко интегрируется во Vue3 - https://html-validate.org/, можно откорректировать специально под проект, если будет необходимость.

**Comment by l3r8yJ** [comment]
https://github.com/stylelint/stylelint
