### ISSUE TITLE
Построить иерархию страниц (1 этап)

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#21]

**Comment by ssh4rd** [comment]
Нужно опираться на эту страницу из wiki [MVP](https://github.com/Handmade-Portal/docs/wiki/Minimal-Viable-Product)

**Comment by thelisass** [comment]
Минусы:
1.	Каталог со схемами. Чаще всего схемы авторские, во многих случаях платные. Размещать чужие схемы в открытом доступе – нецелесообразно. Размещать собственные схемы в открытом доступе так же нецелесообразно, потому что таким образом мы самостоятельно снижаем спрос на свою продукцию. Предложение: убрать блок, либо добавить каталог с собственными схемами с возможностью покупки.

Предложения по блокам: 
1.	Информация о создателе (кто делает игрушки, откуда, история появления бренда)
2.	Архивные фотографии работ (то, что продали или что делалось не на заказ), здесь же можно вести счетчик произведенных игрушек
3.	Вкладка «Coming soon»




![Image](https://github.com/Handmade-Portal/docs/assets/154837153/4ae1ea85-2b42-49db-ade6-58c7ac799b6a)

**Comment by ssh4rd** [comment]
@thelisass нужно убрать блок "Инструменты продавца". В MVP не будет продавцов

**Comment by l3r8yJ** [comment]
@thelisass продублируй в вики

**Comment by thelisass** [comment]
https://github.com/Handmade-Portal/docs/wiki/UI-UX-design
