### ISSUE TITLE
[UX] Составить блок схему сценариев для страницы с каталогом

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#25]
В нашем макете в Figma создана [страничка](https://www.figma.com/file/r3YdTnsXqdtS18szW73MQ4/Handmade-Portal?type=design&node-id=0%3A1&mode=design&t=bB5XibMd1XJHEaoa-1) Task Flow, в ней есть картинка с примером.

**Comment by ssh4rd** [comment]
@thelisass описание сценариев находится [здесь](https://github.com/Handmade-Portal/docs/wiki/Minimal-Viable-Product#%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B9-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)

**Comment by l3r8yJ** [comment]
blocked by #43

**Comment by ssh4rd** [comment]
Переделенная [документация ](https://github.com/Handmade-Portal/docs/wiki/The-second-iteration#%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%81-%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%BC-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2)

**Comment by clowwnada** [comment]
https://www.figma.com/file/r3YdTnsXqdtS18szW73MQ4/Handmade-Portal?type=design&node-id=0%3A1&mode=design&t=wad0nTQYFlt4YX1J-1
