### ISSUE TITLE
Перенести структуру страницы каталога из excalidraw в figma

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#29]
[Макет]( https://excalidraw.com/#room=592dff38324846fc0a14,MapKlqs49crHBvar55aQOQ) в excalidraw
[Макет](https://www.figma.com/file/kaNDpa2W2Ct81aVAnTiRh8/Basic-Structure?type=design&node-id=0-1&mode=design&t=0Cx8lx5uezpqk5GH-0) в Figma

**Comment by l3r8yJ** [comment]
@thelisass посмотри пж
