### ISSUE TITLE
SPIKE Go back framework

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#3]

**Comment by Japsty** [comment]
Варианты фреймворков:

**_1. Gin - Самый популярный на гитхабе, понравился больше всех.  Документация: https://pkg.go.dev/github.com/gin-gonic/gin_**
2. Echo - Немного приятнее по синтаксису и функционалу, чем gin, но информации меньше. Документация: https://echo.labstack.com/docs/context
3. Fiber - Относительно новый фреймворк, по популярности примерно на уровне echo, приятнее по синтаксису и считается самым быстрым. Со слов разрабов "вдохновлен" фреймворком Express Node.js. Документация: https://docs.gofiber.io/guide/grouping

Разницы в производительности особо нет: https://medium.com/deno-the-complete-reference/go-gin-vs-fiber-vs-echo-hello-world-performance-a69a76a64d34

Все из представленных поддерживают Redis. Если Gin особо остальным не зайдет, то как вариант использовать Echo.
