### ISSUE TITLE
[Ops] Создать репо для фронта web-client

### ISSUE THREAD

**Issue by l3r8yJ** [Handmade-Portal/docs#30]
- [x] Создать репо пустой страничкой
- [x] Настроить Ci/Cd чз GitHub Actions
- [ ] Настроить `rultor` для `merge` и `deploy`
Возможно придется создать докер образ для `rultor`, чтобы он мог собирать фронт

**Comment by trapvpack** [comment]
https://github.com/Handmade-Portal/handmade-portal-web-client/tree/30 - Создать репо пустой страничкой

**Comment by trapvpack** [comment]
[Что такое Ci/Cd](https://youtu.be/Y-hYifHkjMs?si=TcFjT6A1wFK4OHcb)
[Дока по GHA(я убил 5 минут, чтобы понять что это GitHub Actions)](https://docs.github.com/en/actions/quickstart)
[Ci/Cd пример](https://www.youtube.com/watch?v=ANj7qUgzNq4&ab_channel=UlbiTV)

**Comment by trapvpack** [comment]
[Pipeline Ci/Cd для фронта](https://www.youtube.com/watch?v=BIY_J0Ba4Cc&ab_channel=FrontendChannel) - разделение на лёгкий pipeline(линтинг и unit-тестирование) и тяжёлый pipeline(линтинг, unit-тестирование, билд, e2e и деплой)

**Comment by trapvpack** [comment]
[Работа в yml, мини курс по GHA](https://www.youtube.com/watch?v=zn5T7FkpaTA&ab_channel=PurpleSchool%7CAntonLarichev)

**Comment by l3r8yJ** [comment]
[example](https://github.com/l3r8yJ/volpi-qa/blob/master/.github/workflows/vite.yaml)

**Comment by trapvpack** [comment]
[GitHub Actions от Егора Бугаенко](https://youtu.be/c2_h7CMzUgA?list=PLaIsQH4uc08y14wCJMeffS2yErN4QpB8m&t=825)

**Comment by trapvpack** [comment]
@l3r8yJ [yml файл](https://github.com/Handmade-Portal/handmade-portal-web-client/blob/30/.github/workflows/github-actions.yml)

**Comment by ssh4rd** [comment]
blocked by #45

**Comment by l3r8yJ** [comment]
@SergeyShapovaIov moron
