### ISSUE TITLE
Тестовое задание на Go

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#34]
@Japsty распиши в комментариях что делал в рамках тестового

**Comment by Japsty** [comment]
Разработка REST сервиса с применением Go,Postgre,Redis,NATS,Clickhouse.
Тут само тестовое: https://github.com/Japsty/Hezzl_test_task
Из того, что делал - 5 эндпоинтов. По эндпоинтам происходит различное взаимодействие с Постгре, при get запросах в кеш закидывается, то, что вывела бдшка. При patch/delete запросах кеш в редисе инвалидируется. Также при patch/delete запросах посылается сообщение в NATS, сабскрайбер, коим является Clickhouse их читает и закидывает к себе в бдшку.
Есть валидация данных, запросы к бд идут через транзакции.
