### ISSUE TITLE
SPIKE Laravel Framework

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#35]
[Документация](https://laravel.com/docs/10.x)

**Comment by trapvpack** [comment]
[Базовый курс по Laravel на русском](https://www.youtube.com/watch?v=5_0GnDfaZbI&list=PLd2_Os8Cj3t8pnG4ubQemoqnTwf0VFEtU&index=2&ab_channel=LaravelCreative)
[Базовый курс по Laravel на английском](https://www.youtube.com/watch?v=MYyJ4PuL4pY&ab_channel=TraversyMedia)
