### ISSUE TITLE
Перенести существующий макет в фигме на другой аккаунт

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#39]
Текущий [макет](https://www.figma.com/file/kaNDpa2W2Ct81aVAnTiRh8/Basic-Structure?type=design&node-id=62-3&mode=design&t=2Um8o8mvE9xsZo4g-0)

После завершения нужно заменить ссылку на макет в [документации](https://github.com/Handmade-Portal/docs/wiki/UI-UX-design) и добавить всех пользователей с текущего макета

**Comment by clowwnada** [comment]
https://www.figma.com/file/r3YdTnsXqdtS18szW73MQ4/SS?type=design&node-id=1%3A333&mode=design&t=KZS9kCLkeEmaLjJu-1

**Comment by clowwnada** [comment]
Заменила ссылку в документации, но не могу добавить пользователей, т. к. нет почт, есть только список людей
Если почты совпадают с гитом, то могу взять их отсюда
