### ISSUE TITLE
[BA] Разработать маркетинговую стратегию

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#47]

**Comment by ShadowShirley** [comment]
[Here you will find basic information about the project in a convenient form.](https://docs.google.com/spreadsheets/d/1iEXquAdyL9H2KCyIyjD86hDpLeui-9aSoEG7YQFp8W8/edit?usp=sharing)

**Comment by ssh4rd** [comment]
![Image](https://github.com/Handmade-Portal/docs/assets/86362529/94018150-1721-4b45-af9b-114d067d3652)

**Comment by ssh4rd** [comment]
![Image](https://github.com/Handmade-Portal/docs/assets/86362529/5c56027c-5eb8-45f0-9e0a-10afb397806e)

Здесь нужно поработать с разметкой: выделенные словосочетания определить как подзаголовки

**Comment by ssh4rd** [comment]
Добавь данные об анализе конкурентов и посещаемости. Графики можешь вставить просто картинками.

**Comment by ShadowShirley** [comment]
[Ссылка на wiki](https://github.com/Handmade-Portal/docs/wiki/Business-analytics)

**Comment by ssh4rd** [comment]
@ShadowShirley убери пожалуйста пункт с ЗП для Николоза )

**Comment by ssh4rd** [comment]
исправлено
