### ISSUE TITLE
[BE][SPIKE] Study project on Gin

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#5]

**Comment by ssh4rd** [comment]
@Japsty describe here what databases you will use, and also libraries. This will help us to choose the right tools for the next projects.

**Comment by Japsty** [comment]
Ниже будут представлены ссылки на полезные библиотеки, что облегчают работу и на библиотеки баз данных для Go

1. Для сервисов заказов, авторизации и страницы магазина будет использоваться бд PostgreSQL: https://github.com/lib/pq
2. Для сервиса тележки покупок будет юзаться Redis в качестве бд : https://github.com/redis/go-redis
3. Либа генерации кода для работы с бд по SQL запросам: https://github.com/sqlc-dev/sqlc
4. Либа для SQL миграций: https://github.com/pressly/goose
5. Либа для загрузки env переменных из .env файла: https://github.com/joho/godotenv
6. Ссылка на GitHub страницу фреймворка Gin: https://github.com/gin-gonic/gin
7. Как удобный логгер будем использовать slog: https://pkg.go.dev/golang.org/x/exp/slog
8. Удобная либа для написания тестов имеет готовые assert'ы и mock'и: https://github.com/stretchr/testify

Ссылка на проект: https://github.com/Japsty/EM_test_task/tree/dev#запуск

Возможно потребуются еще библиотеки, но пока это все, что могу написать на основе того, о чем говорили
