### ISSUE TITLE
SPIKE Layout methodologies

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#6]

**Comment by trapvpack** [comment]
**По моему мнению из рассмотренных методологий CSS, а именно БЭМ, SMACSS и ECSS лучшим вариантом будет использовать БЭМ по следующим причинам:**
•	Чёткая структура – Блок...-Блок-Элемент(ы)-Модификатор(ы).
•	CSS слабо привязан к разметке в определённом месте на странице(влияет только смысловой контекст).
•	Большой объём документации, статей и видео-уроков по использованию методологии в сочетании с препроцессорами-CSS и фреймворками JS.
•	Отсутствие глубокой иерархии - БЭМ-дерево(абстракция над DOM-деревом) является плоским и не допускает более двух семантически описанных вложений. Для организации более глубоких вложений стоит использовать ещё один блок. Это помогает лучше ориентироваться в коде.
•	БЭМ является не только методом именования селекторов, но и методом восприятия проекта как набора сущностей, в большей мере за счёт файловой структуры. Это позволит быстрее вникать в суть написанного кода, бегло пробегаясь по названиям CSS-классов(блоков, методов, модификаторов), т.к. они в свою очередь отвечают на вопрос “Что это?” и имеют чёткое разграничение в именовании для блоков, элементов и модификаторов. 
	**Я бы не хотел работать со SMACSS, т.к.:**
•	Технология затрагивает исключительно CSS, а не весь проект. 
•	Именование селекторов в SMACSS не даёт нам строгости соглашения в именованиях. Советуется ставить префиксы в соответствии с категоризацией, но и это не помогает в понимании сущностей внутри проекта так, как позволяет это делать БЭМ.
	**Я бы не хотел работать с ECSS, т.к.**
•	Эта методология отходит от переиспользования сущностей. Необходимо создавать новый компонент каждый раз, даже когда требуются минимальные изменения.

        *Я считаю, что в рамках текущего проекта инкапсулирование компонентов вёрстки только помешает масштабированию и росту.

**Полезные ссылки:**
	https://nicothin.pro/idiomatic-pre-CSS/#bem-cool – краткое описание работы с БЭМ и препроцессорами
	https://www.dev-notes.ru/articles/css/bem-vs-smacss-comparing-css-methodologies/ - сравнение БЭМ и SMACSS
	https://webformyself.com/css-metodologii-css-bem-smacss-ecss/#:~:text=CSS%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8.,CSS%20%D0%91%D0%AD%D0%9C%2C%20SMACSS%2C%20ECSS – описание всех 3 затронутых методологий

        Для общего понимания БЭМ стоит ознакомиться с **официальной документацией** - https://ru.bem.info/methodology :

•	[Быстрый старт](https://ru.bem.info/methodology/quick-start/)
•	[Основные понятия](https://ru.bem.info/methodology/key-concepts/)
•	[Соглашение по именованию](https://ru.bem.info/methodology/naming-convention/)
•	[Файловая структура](https://ru.bem.info/methodology/filestructure/)
