### ISSUE TITLE
[BE] SPIKE Test Containers GO

### ISSUE THREAD

**Issue by ssh4rd** [Handmade-Portal/docs#8]

**Comment by Japsty** [comment]
Либа для использования тест-контейнеров в go: https://github.com/testcontainers/testcontainers-go
Либа для упрощения тестирования внутри контейнеров: https://github.com/stretchr/testify

Гайд на написание тестов при помощи тестконтейнеров  на go: https://testcontainers.com/guides/getting-started-with-testcontainers-for-go/

По гайду от тестконтейнеров написал пару тест кейсов: https://github.com/Japsty/testcontainers-pract
Очень удобная штука для тестирования работы Бд. Запускает докерконтейнеры по переданным значениям, без всей возни с докеркомпоузом и докерфайлом.

![Image](https://github.com/Handmade-Portal/docs/assets/106777685/5dd4badd-863e-49b9-b4db-8c7f58d5ba1a)
