### ISSUE TITLE
[BE] Описание стека проекта

### ISSUE THREAD

**Issue by l3r8yJ** [Handmade-Portal/docs#9]
Добавить техническое описание в [вики](https://github.com/Handmade-Portal/docs/wiki/Tech-stack) – [пример](https://github.com/Blamer-io/docs/wiki/Technical-Stack)

**Comment by Japsty** [comment]
https://github.com/Handmade-Portal/docs/wiki/Tech-stack

**Comment by ssh4rd** [comment]
![Image](https://github.com/Handmade-Portal/docs/assets/86362529/3c94920e-46fa-40e5-8ff6-e3f67cd7ba8d)

Стоит убрать из пункта backend framework слово backend. Если мы описываем фреймворк в пункте backend, то скорее всего понятно что речь идет именно о фреймворке для бека.
